application: tinkeracademy
version: 1
runtime: python27
api_version: 1
instance_class: F2
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: automatic  # default value
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 8 # default value
threadsafe: true

handlers:
- url: /forgedoc
  static_dir: static/forgedoc
- url: /forge
  static_dir: static/forge
- url: /identicons
  static_dir: static/identicons
- url: /staff
  static_dir: static/staff
- url: /icons
  static_dir: static/icons
- url: /minecraft
  static_dir: static/minecraft
- url: /homework
  static_dir: static/homework
# - url: /
#   static_files: index.html
#   upload: index.html
# - url: /index.html
#   static_files: index.html
#   upload: index.html
# - url: /curriculum.html
#   static_files: curriculum.html
#   upload: curriculum.html
# - url: /login.html
#   static_files: login.html
#   upload: login.html
# - url: /register.html
#   static_files: register.html
#   upload: register.html
# - url: /contact.html
#   static_files: contact.html
#   upload: contact.html
- url: /tinkeracademy/(.*)$
  static_files: tinkeracademy/\1
  upload: tinkeracademy/.*$
- url: /slick/(.*)$
  static_files: slick/\1
  upload: slick/.*$
- url: /admin
  script: tinkeracademy.application 
- url: /.*
  script: tinkeracademy.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: pycrypto
  version: "2.6"