application: tinkeracademy
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /admin
  script: tinkeracademy.application 
- url: /.*
  script: tinkeracademy.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: pycrypto
  version: "2.6"