application: tinkeracademy
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /forgedoc
  static_dir: static/forgedoc
# - url: /
#   static_files: index.html
#   upload: index.html
# - url: /index.html
#   static_files: index.html
#   upload: index.html
# - url: /curriculum.html
#   static_files: curriculum.html
#   upload: curriculum.html
# - url: /login.html
#   static_files: login.html
#   upload: login.html
# - url: /register.html
#   static_files: register.html
#   upload: register.html
# - url: /contact.html
#   static_files: contact.html
#   upload: contact.html
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
- url: /tinkeracademy/(.*)$
  static_files: tinkeracademy/\1
  upload: tinkeracademy/.*$
- url: /admin
  script: tinkeracademy.application 
- url: /.*
  script: tinkeracademy.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: pycrypto
  version: "2.6"